/*!
    *
    * Wijmo Library 5.20202.724
    * http://wijmo.com/
    *
    * Copyright(c) GrapeCity, Inc.  All rights reserved.
    *
    * Licensed under the GrapeCity Commercial License.
    * sales@wijmo.com
    * wijmo.com/products/wijmo-5/license/
    *
    */

var __extends=this&&this.__extends||function(){var extendStatics=function(e,r){return(extendStatics=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,r){e.__proto__=r}||function(e,r){for(var t in r)r.hasOwnProperty(t)&&(e[t]=r[t])})(e,r)};return function(e,r){extendStatics(e,r);function __(){this.constructor=e}e.prototype=null===r?Object.create(r):(__.prototype=r.prototype,new __)}}();import{WjDirective,_registerNgModule,softRefGauge}from"wijmo/wijmo.angular.base";import*as mNg from"angular";import*as wjcGauge from"wijmo/wijmo.gauge";var wjNg=mNg,wijmoGaugeName="wj.gauge";export var ngModuleName=wijmoGaugeName;var wijmoGauge=_registerNgModule(wijmoGaugeName);if(softRefGauge()&&softRefGauge().LinearGauge){wijmoGauge.directive("wjLinearGauge",[function(){return new WjLinearGauge}]);wijmoGauge.directive("wjBulletGraph",[function(){return new WjBulletGraph}]);wijmoGauge.directive("wjRadialGauge",[function(){return new WjRadialGauge}]);wijmoGauge.directive("wjRange",[function(){return new WjRange}])}var WjGauge=function(e){__extends(WjGauge,e);function WjGauge(){var r=e.call(this)||this;r.template="<div ng-transclude />";r.transclude=!0;return r}Object.defineProperty(WjGauge.prototype,"_controlConstructor",{get:function(){return wjcGauge.Gauge},enumerable:!0,configurable:!0});return WjGauge}(WjDirective);export{WjGauge};var WjLinearGauge=function(e){__extends(WjLinearGauge,e);function WjLinearGauge(){return e.call(this)||this}Object.defineProperty(WjLinearGauge.prototype,"_controlConstructor",{get:function(){return wjcGauge.LinearGauge},enumerable:!0,configurable:!0});return WjLinearGauge}(WjGauge);export{WjLinearGauge};var WjBulletGraph=function(e){__extends(WjBulletGraph,e);function WjBulletGraph(){return e.call(this)||this}Object.defineProperty(WjBulletGraph.prototype,"_controlConstructor",{get:function(){return wjcGauge.BulletGraph},enumerable:!0,configurable:!0});return WjBulletGraph}(WjLinearGauge);export{WjBulletGraph};var WjRadialGauge=function(e){__extends(WjRadialGauge,e);function WjRadialGauge(){return e.call(this)||this}Object.defineProperty(WjRadialGauge.prototype,"_controlConstructor",{get:function(){return wjcGauge.RadialGauge},enumerable:!0,configurable:!0});return WjRadialGauge}(WjGauge);export{WjRadialGauge};var WjRange=function(e){__extends(WjRange,e);function WjRange(){var r=e.call(this)||this;r.require=["?^wjLinearGauge","?^wjRadialGauge","?^wjBulletGraph"];r.template="<div ng-transclude />";r.transclude=!0;r._property="ranges";r._isPropertyArray=!0;return r}Object.defineProperty(WjRange.prototype,"_controlConstructor",{get:function(){return wjcGauge.Range},enumerable:!0,configurable:!0});WjRange.prototype._initControl=function(e){return new wjcGauge.Range};return WjRange}(WjDirective);export{WjRange};