/*!
    *
    * Wijmo Library 5.20202.724
    * http://wijmo.com/
    *
    * Copyright(c) GrapeCity, Inc.  All rights reserved.
    *
    * Licensed under the GrapeCity Commercial License.
    * sales@wijmo.com
    * wijmo.com/products/wijmo-5/license/
    *
    */

var __extends=this&&this.__extends||function(){var extendStatics=function(t,r){return(extendStatics=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(t,r){t.__proto__=r}||function(t,r){for(var e in r)r.hasOwnProperty(e)&&(t[e]=r[e])})(t,r)};return function(t,r){extendStatics(t,r);function __(){this.constructor=t}t.prototype=null===r?Object.create(r):(__.prototype=r.prototype,new __)}}();import{WjDirective,_registerNgModule,softRefOlap}from"wijmo/wijmo.angular.base";import{WjFlexGrid}from"wijmo/wijmo.angular.grid";import*as mNg from"angular";import*as wjcOlap from"wijmo/wijmo.olap";var wjNg=mNg,wijmoOlapName="wj.olap";export var ngModuleName=wijmoOlapName;var wijmoOlap=_registerNgModule(wijmoOlapName);if(softRefOlap()&&softRefOlap().PivotGrid){wijmoOlap.directive("wjPivotGrid",["$compile","$interpolate",function(t,r){return new WjPivotGrid(t,r)}]);wijmoOlap.directive("wjPivotChart",[function(){return new WjPivotChart}]);wijmoOlap.directive("wjPivotPanel",[function(){return new WjPivotPanel}]);wijmoOlap.directive("wjSlicer",[function(){return new WjSlicer}])}var WjPivotGrid=function(t){__extends(WjPivotGrid,t);function WjPivotGrid(r,e){return t.call(this,r,e)||this}Object.defineProperty(WjPivotGrid.prototype,"_controlConstructor",{get:function(){return wjcOlap.PivotGrid},enumerable:!0,configurable:!0});return WjPivotGrid}(WjFlexGrid);export{WjPivotGrid};var WjPivotChart=function(t){__extends(WjPivotChart,t);function WjPivotChart(){return null!==t&&t.apply(this,arguments)||this}Object.defineProperty(WjPivotChart.prototype,"_controlConstructor",{get:function(){return wjcOlap.PivotChart},enumerable:!0,configurable:!0});return WjPivotChart}(WjDirective);export{WjPivotChart};var WjPivotPanel=function(t){__extends(WjPivotPanel,t);function WjPivotPanel(){var r=t.call(this)||this;r.transclude=!0;r.template="<div ng-transclude />";return r}Object.defineProperty(WjPivotPanel.prototype,"_controlConstructor",{get:function(){return wjcOlap.PivotPanel},enumerable:!0,configurable:!0});return WjPivotPanel}(WjDirective);export{WjPivotPanel};var WjSlicer=function(t){__extends(WjSlicer,t);function WjSlicer(){return null!==t&&t.apply(this,arguments)||this}Object.defineProperty(WjSlicer.prototype,"_controlConstructor",{get:function(){return wjcOlap.Slicer},enumerable:!0,configurable:!0});return WjSlicer}(WjDirective);export{WjSlicer};