/*!
    *
    * Wijmo Library 5.20202.724
    * http://wijmo.com/
    *
    * Copyright(c) GrapeCity, Inc.  All rights reserved.
    *
    * Licensed under the GrapeCity Commercial License.
    * sales@wijmo.com
    * wijmo.com/products/wijmo-5/license/
    *
    */

var __extends=this&&this.__extends||function(){var extendStatics=function(r,e){return(extendStatics=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(r,e){r.__proto__=e}||function(r,e){for(var a in e)e.hasOwnProperty(a)&&(r[a]=e[a])})(r,e)};return function(r,e){extendStatics(r,e);function __(){this.constructor=r}r.prototype=null===e?Object.create(e):(__.prototype=e.prototype,new __)}}();import{WjDirective,_registerNgModule,softRefChartRadar}from"wijmo/wijmo.angular.base";import{WjFlexChartCore,WjSeriesBase}from"wijmo/wijmo.angular.chart";import*as mNg from"angular";import*as wjcChartRadar from"wijmo/wijmo.chart.radar";var wjNg=mNg,wijmoChartRadarName="wj.chart.radar";export var ngModuleName=wijmoChartRadarName;var wijmoChartRadar=_registerNgModule(wijmoChartRadarName);if(softRefChartRadar()){wijmoChartRadar.directive("wjFlexRadar",[function(){return new WjFlexRadar}]);wijmoChartRadar.directive("wjFlexRadarSeries",[function(){return new WjFlexRadarSeries}]);wijmoChartRadar.directive("wjFlexRadarAxis",[function(){return new WjFlexRadarAxis}])}var WjFlexRadar=function(r){__extends(WjFlexRadar,r);function WjFlexRadar(){return null!==r&&r.apply(this,arguments)||this}Object.defineProperty(WjFlexRadar.prototype,"_controlConstructor",{get:function(){return wjcChartRadar.FlexRadar},enumerable:!0,configurable:!0});return WjFlexRadar}(WjFlexChartCore);export{WjFlexRadar};var WjFlexRadarSeries=function(r){__extends(WjFlexRadarSeries,r);function WjFlexRadarSeries(){var e=r.call(this)||this;e.require="^wjFlexRadar";e.template='<div class="wjFlexRadarSeries" ng-transclude />';return e}Object.defineProperty(WjFlexRadarSeries.prototype,"_controlConstructor",{get:function(){return wjcChartRadar.FlexRadarSeries},enumerable:!0,configurable:!0});return WjFlexRadarSeries}(WjSeriesBase);export{WjFlexRadarSeries};var WjFlexRadarAxis=function(r){__extends(WjFlexRadarAxis,r);function WjFlexRadarAxis(){var e=r.call(this)||this;e.require=["?^wjFlexRadarSeries","?^wjFlexRadar"];e.template='<div class="wjFlexRadarAxis" />';return e}Object.defineProperty(WjFlexRadarAxis.prototype,"_controlConstructor",{get:function(){return wjcChartRadar.FlexRadarAxis},enumerable:!0,configurable:!0});WjFlexRadarAxis.prototype._initControl=function(e){return r.prototype._initControl.call(this,void 0)};return WjFlexRadarAxis}(WjDirective);export{WjFlexRadarAxis};