/*!
    *
    * Wijmo Library 5.20202.724
    * http://wijmo.com/
    *
    * Copyright(c) GrapeCity, Inc.  All rights reserved.
    *
    * Licensed under the GrapeCity Commercial License.
    * sales@wijmo.com
    * wijmo.com/products/wijmo-5/license/
    *
    */

var __extends=this&&this.__extends||function(){var extendStatics=function(o,e){return(extendStatics=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(o,e){o.__proto__=e}||function(o,e){for(var r in e)e.hasOwnProperty(r)&&(o[r]=e[r])})(o,e)};return function(o,e){extendStatics(o,e);function __(){this.constructor=o}o.prototype=null===e?Object.create(e):(__.prototype=e.prototype,new __)}}();import{ComponentBase}from"wijmo/wijmo.react.base";import*as wjcBarcodeCommon from"wijmo/wijmo.barcode.common";var BarcodeCodabar=function(o){__extends(BarcodeCodabar,o);function BarcodeCodabar(e){return o.call(this,e,wjcBarcodeCommon.Codabar,{objectProps:["quietZone","font"]})||this}return BarcodeCodabar}(ComponentBase);export{BarcodeCodabar};var BarcodeEan8=function(o){__extends(BarcodeEan8,o);function BarcodeEan8(e){return o.call(this,e,wjcBarcodeCommon.Ean8,{objectProps:["quietZone","font"]})||this}return BarcodeEan8}(ComponentBase);export{BarcodeEan8};var BarcodeEan13=function(o){__extends(BarcodeEan13,o);function BarcodeEan13(e){return o.call(this,e,wjcBarcodeCommon.Ean13,{objectProps:["quietZone","font"]})||this}return BarcodeEan13}(ComponentBase);export{BarcodeEan13};var BarcodeCode39=function(o){__extends(BarcodeCode39,o);function BarcodeCode39(e){return o.call(this,e,wjcBarcodeCommon.Code39,{objectProps:["quietZone","font"]})||this}return BarcodeCode39}(ComponentBase);export{BarcodeCode39};var BarcodeCode128=function(o){__extends(BarcodeCode128,o);function BarcodeCode128(e){return o.call(this,e,wjcBarcodeCommon.Code128,{objectProps:["quietZone","font"]})||this}return BarcodeCode128}(ComponentBase);export{BarcodeCode128};var BarcodeGs1_128=function(o){__extends(BarcodeGs1_128,o);function BarcodeGs1_128(e){return o.call(this,e,wjcBarcodeCommon.Gs1_128,{objectProps:["quietZone","font"]})||this}return BarcodeGs1_128}(ComponentBase);export{BarcodeGs1_128};var BarcodeUpcA=function(o){__extends(BarcodeUpcA,o);function BarcodeUpcA(e){return o.call(this,e,wjcBarcodeCommon.UpcA,{objectProps:["quietZone","font"]})||this}return BarcodeUpcA}(ComponentBase);export{BarcodeUpcA};var BarcodeUpcE0=function(o){__extends(BarcodeUpcE0,o);function BarcodeUpcE0(e){return o.call(this,e,wjcBarcodeCommon.UpcE0,{objectProps:["quietZone","font"]})||this}return BarcodeUpcE0}(ComponentBase);export{BarcodeUpcE0};var BarcodeUpcE1=function(o){__extends(BarcodeUpcE1,o);function BarcodeUpcE1(e){return o.call(this,e,wjcBarcodeCommon.UpcE1,{objectProps:["quietZone","font"]})||this}return BarcodeUpcE1}(ComponentBase);export{BarcodeUpcE1};var BarcodeQrCode=function(o){__extends(BarcodeQrCode,o);function BarcodeQrCode(e){return o.call(this,e,wjcBarcodeCommon.QrCode,{objectProps:["quietZone","font"]})||this}return BarcodeQrCode}(ComponentBase);export{BarcodeQrCode};