/*!
    *
    * Wijmo Library 5.20202.724
    * http://wijmo.com/
    *
    * Copyright(c) GrapeCity, Inc.  All rights reserved.
    *
    * Licensed under the GrapeCity Commercial License.
    * sales@wijmo.com
    * wijmo.com/products/wijmo-5/license/
    *
    */

var __extends=this&&this.__extends||function(){var extendStatics=function(e,r){return(extendStatics=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,r){e.__proto__=r}||function(e,r){for(var o in r)r.hasOwnProperty(o)&&(e[o]=r[o])})(e,r)};return function(e,r){extendStatics(e,r);function __(){this.constructor=e}e.prototype=null===r?Object.create(r):(__.prototype=r.prototype,new __)}}();import{VueApi,WjComponentBehavior}from"wijmo/wijmo.vue2.base";import*as wjcViewer from"wijmo/wijmo.viewer";var WjReportViewerBehavior=function(e){__extends(WjReportViewerBehavior,e);function WjReportViewerBehavior(){return null!==e&&e.apply(this,arguments)||this}WjReportViewerBehavior.tag="wj-report-viewer";WjReportViewerBehavior.props=["isDisabled","serviceUrl","filePath","fullScreen","zoomFactor","zoomMode","mouseMode","viewMode","requestHeaders","parameters","paginated","reportName"];WjReportViewerBehavior.events=["initialized","gotFocus","lostFocus","refreshing","refreshed","invalidInput","pageIndexChanged","queryLoadingData","beforeSendRequest"];WjReportViewerBehavior.changeEvents={fullScreenChanged:["fullScreen"],zoomFactorChanged:["zoomFactor"],zoomModeChanged:["zoomMode"],mouseModeChanged:["mouseMode"],viewModeChanged:["viewMode"]};WjReportViewerBehavior.classCtor=function(){return wjcViewer.ReportViewer};return WjReportViewerBehavior}(WjComponentBehavior);export var WjReportViewer=WjReportViewerBehavior.register();function registerV3WjReportViewer(e){e.component(WjReportViewerBehavior.tag,WjReportViewer)}var WjPdfViewerBehavior=function(e){__extends(WjPdfViewerBehavior,e);function WjPdfViewerBehavior(){return null!==e&&e.apply(this,arguments)||this}WjPdfViewerBehavior.tag="wj-pdf-viewer";WjPdfViewerBehavior.props=["isDisabled","serviceUrl","filePath","fullScreen","zoomFactor","zoomMode","mouseMode","viewMode","requestHeaders"];WjPdfViewerBehavior.events=["initialized","gotFocus","lostFocus","refreshing","refreshed","invalidInput","pageIndexChanged","queryLoadingData","beforeSendRequest"];WjPdfViewerBehavior.changeEvents={fullScreenChanged:["fullScreen"],zoomFactorChanged:["zoomFactor"],zoomModeChanged:["zoomMode"],mouseModeChanged:["mouseMode"],viewModeChanged:["viewMode"]};WjPdfViewerBehavior.classCtor=function(){return wjcViewer.PdfViewer};return WjPdfViewerBehavior}(WjComponentBehavior);export var WjPdfViewer=WjPdfViewerBehavior.register();function registerV3WjPdfViewer(e){e.component(WjPdfViewerBehavior.tag,WjPdfViewer)}export function registerViewer(e){if(VueApi.isV3Plus){registerV3WjReportViewer(e);registerV3WjPdfViewer(e)}}