/*!
    *
    * Wijmo Library 5.20202.724
    * http://wijmo.com/
    *
    * Copyright(c) GrapeCity, Inc.  All rights reserved.
    *
    * Licensed under the GrapeCity Commercial License.
    * sales@wijmo.com
    * wijmo.com/products/wijmo-5/license/
    *
    */

import{ComponentBase}from"wijmo/wijmo.react.base";import*as wjcChart from"wijmo/wijmo.chart";export class FlexChart extends ComponentBase{constructor(t){super(t,wjcChart.FlexChart,{objectProps:["palette","plotMargin","footerStyle","headerStyle","itemsSource","options","selection","renderEngine"]})}componentDidMount(){let t=super.componentDidMount();this._setExtra(this.props);return t}componentDidUpdate(t){super.componentDidUpdate(t);this._setExtra(this.props)}_setExtra(t){"tooltipContent"in t&&(this.control.tooltip.content=t.tooltipContent);"labelContent"in t&&(this.control.dataLabel.content=t.labelContent)}}export class FlexPie extends ComponentBase{constructor(t){super(t,wjcChart.FlexPie,{objectProps:["palette","plotMargin","footerStyle","headerStyle","itemsSource","titles"]})}componentDidMount(){let t=super.componentDidMount();this._setExtra(this.props);return t}componentDidUpdate(t){super.componentDidUpdate(t);this._setExtra(this.props)}_setExtra(t){"tooltipContent"in t&&(this.control.tooltip.content=t.tooltipContent);"labelContent"in t&&(this.control.dataLabel.content=t.labelContent)}}export class FlexChartAxis extends ComponentBase{constructor(t){super(t,wjcChart.Axis,{objectProps:["plotArea","itemsSource"]});this._parentProp="axes"}}export class FlexChartLegend extends ComponentBase{constructor(t){super(t,wjcChart.Legend);this._parentProp="legend";this._parentInCtor=!0}}export class FlexChartDataLabel extends ComponentBase{constructor(t){super(t,wjcChart.DataLabel,{objectProps:["content"]});this._parentProp="dataLabel"}}export class FlexPieDataLabel extends ComponentBase{constructor(t){super(t,wjcChart.PieDataLabel,{objectProps:["content"]});this._parentProp="dataLabel"}}export class FlexChartSeries extends ComponentBase{constructor(t){super(t,wjcChart.Series,{objectProps:["axisX","axisY","style","altStyle","symbolStyle","itemsSource","tooltipContent"]});this._parentProp="series";this._siblingId="series"}}export class FlexChartLineMarker extends ComponentBase{constructor(t){super(t,wjcChart.LineMarker);this._parentInCtor=!0}}export class FlexChartDataPoint extends ComponentBase{constructor(t){super(t,wjcChart.DataPoint);this._parentProp=""}}export class FlexChartPlotArea extends ComponentBase{constructor(t){super(t,wjcChart.PlotArea,{objectProps:["style"]});this._parentProp="plotAreas"}}