/*!
    *
    * Wijmo Library 5.20202.724
    * http://wijmo.com/
    *
    * Copyright(c) GrapeCity, Inc.  All rights reserved.
    *
    * Licensed under the GrapeCity Commercial License.
    * sales@wijmo.com
    * wijmo.com/products/wijmo-5/license/
    *
    */

"use strict";var WjFlexGridSearch_1,__decorate=this&&this.__decorate||function(e,r,t,i){var a,o=arguments.length,c=o<3?r:null===i?i=Object.getOwnPropertyDescriptor(r,t):i;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)c=Reflect.decorate(e,r,t,i);else for(var s=e.length-1;s>=0;s--)(a=e[s])&&(c=(o<3?a(c):o>3?a(r,t,c):a(r,t))||c);return o>3&&c&&Object.defineProperty(r,t,c),c},__param=this&&this.__param||function(e,r){return function(t,i){r(t,i,e)}};Object.defineProperty(exports,"__esModule",{value:!0});const core_1=require("@angular/core"),common_1=require("@angular/common"),forms_1=require("@angular/forms"),wijmo_angular2_directiveBase_1=require("wijmo/wijmo.angular2.directiveBase"),wjcGridSearch=require("wijmo/wijmo.grid.search");var wjFlexGridSearchMeta={selector:"wj-flex-grid-search",template:"",inputs:["wjModelProperty","isDisabled","text","delay","placeholder","cssMatch","grid"],outputs:["initialized","gotFocusNg: gotFocus","lostFocusNg: lostFocus","refreshingNg: refreshing","refreshedNg: refreshed","invalidInputNg: invalidInput"],providers:[{provide:forms_1.NG_VALUE_ACCESSOR,useFactory:wijmo_angular2_directiveBase_1.WjValueAccessorFactory,multi:!0,deps:["WjComponent"]}]};exports.wjFlexGridSearchMeta=wjFlexGridSearchMeta;let WjFlexGridSearch=WjFlexGridSearch_1=class WjFlexGridSearch extends wjcGridSearch.FlexGridSearch{constructor(e,r,t){super(wijmo_angular2_directiveBase_1.WjDirectiveBehavior.getHostElement(e,r));this.isInitialized=!1;this._wjBehaviour=wijmo_angular2_directiveBase_1.WjDirectiveBehavior.attach(this,e,r,t);this.created()}created(){}ngOnInit(){this._wjBehaviour.ngOnInit()}ngAfterViewInit(){this._wjBehaviour.ngAfterViewInit()}ngOnDestroy(){this._wjBehaviour.ngOnDestroy()}addEventListener(e,r,t,i=!1){let a=wijmo_angular2_directiveBase_1.WjDirectiveBehavior,o=a.ngZone;o&&a.outsideZoneEvents[r]?o.runOutsideAngular(()=>{super.addEventListener(e,r,t,i)}):super.addEventListener(e,r,t,i)}};WjFlexGridSearch.meta={outputs:wjFlexGridSearchMeta.outputs};WjFlexGridSearch=WjFlexGridSearch_1=__decorate([core_1.Component({selector:wjFlexGridSearchMeta.selector,template:wjFlexGridSearchMeta.template,inputs:wjFlexGridSearchMeta.inputs,outputs:wjFlexGridSearchMeta.outputs,providers:[{provide:"WjComponent",useExisting:core_1.forwardRef(()=>WjFlexGridSearch_1)},...wjFlexGridSearchMeta.providers]}),__param(0,core_1.Inject(core_1.ElementRef)),__param(1,core_1.Inject(core_1.Injector)),__param(2,core_1.Inject("WjComponent")),__param(2,core_1.SkipSelf()),__param(2,core_1.Optional())],WjFlexGridSearch);exports.WjFlexGridSearch=WjFlexGridSearch;let moduleExports=[WjFlexGridSearch],WjGridSearchModule=class WjGridSearchModule{};WjGridSearchModule=__decorate([core_1.NgModule({imports:[common_1.CommonModule],declarations:[...moduleExports],exports:[...moduleExports]})],WjGridSearchModule);exports.WjGridSearchModule=WjGridSearchModule;